config/routes.rb
Rails.application.routes.draw do
  resources :messages, except: [:index, :show]
  resources :users do
    member do
      delete 'takedown_target'
      post 'reinstate_player'
    end
  end
  root 'welcome#index'
  get '/takeover_disputes', to: 'users#takeover_disputes'
  get '/dispute_takeover', to: 'users#dispute_takeover'
  get '/update_pairings', to: 'users#update_pairings'
  get '/target_taken_down', to: 'users#target_taken_down'
  get 'takedown_target', to: 'users#takedown_target'
  get '/posts', to: 'users#posts'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :text, presence: true
  validates :text, length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  include BCrypt
  has_many :messages, dependent: :destroy
  validates :name, presence: true
  validates :name, length: { minimum: 2 }
  validates :name, uniqueness: true
  validates :email, presence: true
  validates :email, uniqueness: true
  validates_email_format_of :email 
  validate :capitalized

  def capitalized
    errors.add(:name, 'is not capitalized.') if name && name.starts_with?(name.downcase)
  end

  def password
    @password ||= Password.new(password_hash) if password_hash
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end

  def takedown_target(target)
    target.update(active: false)
  end

  def reinstate_player(target)
    target.update(active: true)
  end

  def view_target
    User.find_by(name: self.target)
  end

  def messages_for_admin
    Message.joins(:user).where(users: { admin: false })
  end

  def messages_for_players
    Message.joins(:user).where(users: { admin: true })
  end

  def get_attacker
    User.find_by(target: self.name)
  end

  def self.eliminate_inactive_players
    User.offset(1).each do |user|
      user.destroy unless user.active
    end
  end

  def self.pair_users
    if User.all.size > 2
      target = User.second
        User.offset(2).each do |user|
        user.update(target: target.name)
        target = user
      end
      User.second.update(target: target.name)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  helper_method def logged_in?
    session[:user_id]
  end

  helper_method def current_user
    @current_user ||= User.find(session[:user_id]) if logged_in?
  end

  helper_method def admin?
    User.find(session[:user_id]).admin if logged_in?
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy, :authenticate_user]
  before_action :authenticate_user

  def authenticate_user
    redirect_to index unless logged_in?
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to '/posts', notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to '/posts', notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to '/posts', notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private

  def set_message
    @message = Message.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def message_params
    params.require(:message).permit(:text, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # GET /sessions/new
  def new
    @user = User.new
  end

  # POST /sessions
  # POST /sessions.json
  def create
    user = User.find_by(email: params[:email])
    if user && user.password == params[:password]
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to '/login'
    end
  end

  # DELETE /sessions/1
  # DELETE /sessions/1.json
  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :reinstate_player, :view_target]

  def index
    @users = User.all
  end

  def show
    @message = Message.new
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    @user.password = user_params[:password]
    @user.active = true
    @user.admin = false
    respond_to do |format|
      if @user.save
        format.html { redirect_to '/login', notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def takedown_target
    if logged_in?
      if admin?
        target = User.find(params[:id])
        current_user.takedown_target(target)
        Message.where(user: target).destroy_all
        redirect_to '/takeover_disputes'
      else
        target = User.find_by(name: current_user.target)
        current_user.takedown_target(target)
        redirect_to '/target_taken_down'
      end
    else
      redirect_to root_path
    end
  end

  def reinstate_player
    if logged_in? && admin?
      target = User.find(params[:id])
      current_user.reinstate_player(target)
      Message.where(user: target).destroy_all
      redirect_to '/takeover_disputes'
    else
      redirect_to root_path
    end
  end

  def update_pairings
    if logged_in? && admin?
      User.eliminate_inactive_players
      User.pair_users
    else
      redirect_to root_path
    end
  end

  def takeover_disputes
    redirect_to root_path unless logged_in?
  end

  def dispute_takeover
    redirect_to root_path unless logged_in?
    set_messages
  end

  def target_taken_down
    redirect_to root_path unless logged_in?
    set_messages
  end

  def view_target
    current_user.view_target
  end

  def posts
    redirect_to root_path unless logged_in?
    set_messages
  end

private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :admin, :target)
  end

  def set_messages
    @message = Message.new
    @messages = logged_in? ? Message.joins(:user).where(users: { admin: true }) : []
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @message = Message.new
    @messages = logged_in? ? Message.joins(:user).where(users: { admin: true }) : []
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark mb-4" style="background-color: #2b6f53;">
  <div class="container">
    <%= link_to 'Hostile Takeover', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar_content" aria-controls="navbar_content" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar_content" class="collapse navbar-collapse">
      <ul class="navbar-nav ml-auto">
        <%# Only display the current user's name, friend requests, and log out links if a user is logged in %>
        <% if current_user %>
        <% if admin? %>
          <li class="nav-item"><%= link_to "Posts", '/posts', class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to "Takeover Disputes", '/takeover_disputes', class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Users', '/users', class: 'nav-link' %></li>
        <% end %>
          <li class="nav-item"><%= link_to "Log Out", '/logout', method: :delete, class: 'nav-link' %></li>
        <%# Only display the sign up and log in links if no user is logged in %>
        <% else %>
          <li class="nav-item"><%= link_to "Sign Up", '/users/new', class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to "Log In", '/login', class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tanu Balla Final Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for message do |f| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>
      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="field form-group">
    <%= f.text_area :text, rows: 3, class: 'form-control', placeholder: "What's going on, #{current_user.name}?" %>
  </div>

    <%= f.submit class: 'btn btn-sm btn-primary float-right' %>
<% end %>

app/views/messages/_message.html.erb
<div class="card">
  <div class="card-body">
    <span class="card-title"><strong><%= message.user.name %></strong></span><br>
    <small class="card-subtitle text-muted">Updated <%= time_ago_in_words(message.updated_at) %> ago</small><br>
    <p class="card-text"><%= message.text %></p>
    <% if current_user == message.user %>
      <%= link_to 'Edit', edit_message_path(message), class: 'card-link' %>
      <%= link_to 'Delete', message, method: :delete, class: 'card-link' %>
    <% end %>
  </div>
</div>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>
<%= render 'form', message: @message %>

<br>
<%= link_to 'Back', '/' %>

app/views/messages/new.html.erb
<h1>Create New Message</h1>
<%= render 'messages/form', message: @message %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/dispute_takeover.html.erb
<div class="cover-container", align="center">
  <main role="main" class="inner cover">
    <h1 class="cover-heading">You were taken out!</h1>
    <p class="lead">
      Think this is a mistake? Let the Gamemaster know by disputing the takeover.
    </p>
  </main>
</div>
<div class="row">
  <div class="col-lg-6 offset-lg-3">
    <%= render 'messages/form', message: @message %>
  </div>
</div>
<br>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Raiders</h1>

<table class="table table-light">
  <thead>
    <tr>
      <th class="table-dark bg-primary">Name</th>
      <th class="table-dark bg-primary">Email</th>
      <th class="table-dark bg-primary">Target</th>
      <th class="table-dark bg-primary" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.target %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/posts.html.erb
<% if admin? %>
  <div class="row">
    <div class="col-lg-6 offset-lg-3">
      <%= render 'messages/form', message: @message %>
    </div>
  </div>
  <br>
      <% if @messages.empty? %>
        <p class="text-center">There aren't any posts yet, you should create one!</p>
      <% else %>
        <% @messages.reverse.each do |message| %>
          <%= render 'messages/message', message: message %>
          <br>
        <% end %>
      <% end %>
<% else %>
  <body>
    <div class="cover-container", align="center">
      <main role="main" class="inner cover">
        <h1 class="cover-heading">Your dispute is being reviewed.</h1>
        <p class="lead">
          Please check back again later to see if you are reinstated and assigned to your target.
        </p>
      </main>
    </div>
  </body>
  <% @messages.reverse.each do |message| %>
    <%= render 'messages/message', message: message %>
    <br>
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-12">
    <div class="float-right">
      <% if logged_in? %>
        <% if admin? %>
        <% else %>
          <div class="cover-container">
            <main role="main" class="inner cover">
              <h1 class="cover-heading">Your target is <%= current_user.target %>!</h1>
              <p class="lead">
                <%= link_to "Target taken over!", '/takedown_target', class: 'button' %>
              </p>
            </main>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<br>
</div>

app/views/users/takeover_disputes.html.erb
<table class="table table-light">
  <thead>
    <tr>
      <th class="table-dark bg-primary">Current Takeover Disputes</th>
      <th class="table-dark bg-primary" colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% if current_user.messages_for_admin.empty? %>
      <td>No current takeover disputes.</td>
    <% else %>
      <% current_user.messages_for_admin.each do |message| %>
        <tr>
          <td>
            <h5>Target: <%= message.user.name %>, Raider: <%= message.user.get_attacker.name %></h5>
            <p><%= message.text %></p>
          </td>
          <td><%= link_to 'Deactivate Player', takedown_target_user_path(message.user.id), method: :delete %></td>
          <td><%= link_to 'Reinstate Player', reinstate_player_user_path(message.user.id), method: :post %></td>
        </tr>
      <% end %>
  <% end %>
</table>

app/views/users/target_taken_down.html.erb
<div class="cover-container", align="center">
  <main role="main" class="inner cover">
    <h1 class="cover-heading">Congratulations on your victory, <%=current_user.name%>!</h1>
  </main>
</div>
<% @messages.each do |message| %>
  <%= render 'messages/message', message: message %>
  <br>
<% end %>

app/views/users/update_pairings.html.erb
<div class="cover-container", align="center", style="position: absolute; margin: auto; top: 0; right: 0; bottom: 0; left: 0; width: 1000px; height: 100px;">
  <main role="main" class="inner cover">
    <h1 class="cover-heading">Welcome, Gamemaster.</h1>
    <p class="lead">
      A new round has begun!
    </p>
  </main>
</div>

app/views/welcome/index.html.erb
<% if logged_in? %>
  <% if admin? %>
    <body>
      <div class="cover-container", align="center", style="position: absolute; margin: auto; top: 0; right: 0; bottom: 0; left: 0; width: 1000px; height: 100px;">
        <main role="main" class="inner cover">
          <h1 class="cover-heading">Welcome, Gamemaster.</h1>
          <p class="lead">
            <%= link_to "Start a new round!", '/update_pairings', class: 'button' %>
          </p>
        </main>
      </div>
    </body>
  <% else %>
    <% if !current_user.target %>
      <body>
        <div class="cover-container", align="center">
          <main role="main" class="inner cover">
            <h1 class="cover-heading">You currently do not have a target.</h1>
            <p class="lead">
              Please check again at a later time.
            </p>
          </main>
        </div>
      </body>    
    <% elsif current_user.view_target.active && current_user.active %>
      <body>
        <div class="cover-container", align="center">
          <main role="main" class="inner cover">
            <h1 class="cover-heading">Your target is <%= current_user.target %>!</h1>
            <p class="lead">
              <%= link_to "Target taken over!", '/takedown_target', class: 'button' %>
            </p>
          </main>
        </div>
      </body>
    <% elsif !current_user.view_target.active && current_user.active %>
      <div class="cover-container", align="center">
        <main role="main" class="inner cover">
          <h1 class="cover-heading">Congratulations on your victory, <%=current_user.name%>!</h1>
        </main>
      </div>
    <% else %>
      <body>
        <div class="cover-container", align="center">
          <main role="main" class="inner cover">
            <h1 class="cover-heading">You were taken out!</h1>
            <p class="lead">
              Think this is a mistake? Let the Gamemaster know by disputing the takeover.
            </p>
            <p class="lead">
              <%= link_to "Dispute takeover!", '/dispute_takeover', class: 'button' %>
            </p>
          </main>
        </div>
      </body>
    <% end %>
    <% @messages.reverse.each do |message| %>
      <%= render 'messages/message', message: message %>
      <br>
    <% end %>
  <% end %>
<% else %>
  <div class="row">
    <div class="col-lg-6 offset-lg-3", align="center">
      <h1>Wharton Council Presents: Hostile Takeover!</h1>
      <p>Sign up or log in to play Wharton's Game of Assassins!</p>
    </div>
  </div>
<% end %>